name: Deployment pipeline
#
on:
  push: # runs on every push to master
    branches: 
      - master
  pull_request: 
      branches: [master]
      types: [opened, synchronize] # he workflow will run when a PR into the main branch is opened or updated.
jobs: 
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04 # the type of machine to run the job on. What do is run the job on a ubuntu machine.
        steps: 
            - uses : actions/checkout@v3  # this is a github action that checks out the code from the repo. This makes the code available to the job.
            - uses: superfly/flyctl-actions/setup-flyctl@master # Installs the flyctl CLI tool to enable deploying and managing Fly apps
            - uses : actions/setup-node@v3 # this is a github action that sets up node on the machine. This makes node available to the job.
              with: 
                node-version: '16' # this is the version of node to install on the machine.
            - name: Install dependencies # this is a step that installs the dependencies of the project.
              run: npm install
            - name: Check code formatting # this is a step that checks the code formatting.
              run: npm run eslint
            - name: Tests # this is a step that runs the tests.
              run: npm run test
            - name: Build # this is a step that builds the project.
              run: npm run build
            - name: e2e tests # this is a step that runs the end to end tests.
              uses: cypress-io/github-action@v5
              with: 
                command: npm run test:e2e
                start: npm run start-prod
                wait-on: http://localhost:8080
            - name: Deploy
              if: ${{ github.event_name == 'push' && !contains( join( github.event.commits.*.message, ''), '#skip')}}
              run: flyctl deploy --remote-only
              env: 
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
            
    tag_release:
      needs: [simple_deployment_pipeline] # as jobs of a workflow are executed in parallel we make sure it runs after the deploymend succeds
      runs-on: ubuntu-20.04 # the type of machine to run the job on. What do is run the job on a ubuntu machine.
      if: ${{ github.event_name == 'push' && !contains( join( github.event.commits.*.message, ''), '#skip')}}
      steps: 
        - uses: actions/checkout@v3
        - name: Bump version and push tag # versioning
          uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36 # third-party for versioning. Automatically increase (bump) the version when a pull request is merged into the main branch and tag the release with the version number
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BUMP: patch
            WITH_V: true
        - name: Notify success status on Discord
          uses: rjstone/discord-webhook-notify@v1
          if: success()
          with:
            severity: info
            details: A new version of Pokedex has been deployed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
     
